name: Actions
on: [push]
jobs:
  readmeWorkflow:
    name: Readme Workflow ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: unity-toolbox/Assets/tests/tests
          key: Library-test-project-unity-toolkit

      # Test
      - name: Run tests
        uses: webbertakken/unity-test-runner@v1.3
        with:
          projectPath: unity-toolbox
          unityVersion: 2019.4.14f1

      # Build
      - name: Build project
        uses: webbertakken/unity-builder@v0.10
        with:
          projectPath: unity-toolbox
          unityVersion: 2019.4.14f1
          targetPlatform: Windows

      # Output
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build

    
